# Generated by Django 3.0.2 on 2020-01-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200121_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('img_sub_banner', models.ImageField(upload_to='sub_banners_images')),
            ],
        ),
    ]
