# Generated by Django 3.0.2 on 2020-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sub_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestseller_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('img_product', models.ImageField(upload_to='new_product')),
            ],
        ),
        migrations.CreateModel(
            name='special_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('img_product', models.ImageField(upload_to='new_product')),
            ],
        ),
    ]
