# Generated by Django 3.0.2 on 2020-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200201_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('image_src', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
