# Generated by Django 3.0.2 on 2020-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200201_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_info', models.TextField(max_length=700)),
                ('pay_method', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=700)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='order_product',
        ),
    ]
