# Generated by Django 3.0.2 on 2020-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200203_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('sender', models.CharField(max_length=200)),
                ('review_text', models.TextField(max_length=700)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
