# Generated by Django 3.0.2 on 2020-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('img_banner', models.ImageField(upload_to='banner_images')),
            ],
        ),
        migrations.CreateModel(
            name='latest_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('img_product', models.ImageField(upload_to='new_product')),
            ],
        ),
        migrations.DeleteModel(
            name='latest',
        ),
    ]
