# Generated by Django 3.0.2 on 2020-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
