# Generated by Django 3.0.2 on 2020-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200203_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('enquiry', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_info', models.TextField(max_length=700)),
                ('pay_method', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=700)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('review_text', models.TextField(max_length=700)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
