# Generated by Django 3.0.2 on 2020-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200203_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='enquiry',
            field=models.TextField(editable=False, max_length=700),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='full_name',
            field=models.CharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='address',
            field=models.TextField(editable=False, max_length=700),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='full_name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='item_info',
            field=models.TextField(editable=False, max_length=700),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='pay_method',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='phone',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='sender',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='review_product',
            name='product_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='review_product',
            name='rating',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='review_product',
            name='review_text',
            field=models.TextField(editable=False, max_length=700),
        ),
        migrations.AlterField(
            model_name='review_product',
            name='sender',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
