# Generated by Django 3.0.2 on 2020-01-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bestseller_product_special_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bestseller_product',
            new_name='product',
        ),
        migrations.DeleteModel(
            name='latest_product',
        ),
        migrations.DeleteModel(
            name='special_product',
        ),
    ]
