# Generated by Django 3.0.2 on 2020-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200126_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
