# Generated by Django 3.0.2 on 2020-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('img_product', models.ImageField(upload_to='ordered')),
                ('qty', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='order_now',
        ),
    ]
